# Generated by Django 4.0.2 on 2022-02-03 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_delete_favorites'),
        ('favorites', '0002_alter_favorites_pokemonname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='playground.user'),
        ),
    ]
